//! Build script — DERIVES the spec snapshot instead of restating it.
//!
//! D16 / AP-13: "a suite MUST NOT restate a spec-data/ snapshot as a constant. A run-defining
//! input that the requirement files already carry must be DERIVED, never restated in suite
//! source." So nothing under `src/` names a snapshot. This script reads the `snapshot` field out
//! of the requirement files the suite implements, checks that they all agree, and generates the
//! constants into OUT_DIR.
//!
//! The failure mode this prevents is specific: a suite that hardcodes a snapshot keeps stamping
//! the old one into `spec.*` — the verdict's comparability anchor — after a re-base, and the
//! verdict then claims to have been measured against text it never saw.

use std::path::{Path, PathBuf};

const REQUIREMENTS: [&str; 3] = ["ECP-R57", "ECP-R3", "ECP-R7"];

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let repo = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("suite lives at <repo>/suites/<name>")
        .to_path_buf();

    let req_dir = repo.join("requirements").join("entity-core-protocol");

    let mut snapshot: Option<String> = None;
    for id in REQUIREMENTS {
        let path = req_dir.join(format!("{}.diag", id));
        println!("cargo:rerun-if-changed={}", path.display());
        let body = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("cannot read {}: {}", path.display(), e));
        let found = extract_snapshot(&body)
            .unwrap_or_else(|| panic!("{} declares no `snapshot` field", path.display()));
        match &snapshot {
            None => snapshot = Some(found),
            Some(prev) if *prev == found => {}
            Some(prev) => panic!(
                "REFUSING TO BUILD: the implemented requirements cite two snapshots — {} declares \
                 `{}` where an earlier file declared `{}`. A verdict document carries ONE \
                 comparability anchor, and emitting one of two snapshots as if it were the run's \
                 would be a false anchor. Split the run or re-base the files.",
                path.display(),
                found,
                prev
            ),
        }
    }
    let snapshot = snapshot.expect("no requirements");

    // "<spec>/v<version>" since ADR-0001. The version is the leaf with its `v` stripped.
    let version = snapshot
        .rsplit('/')
        .next()
        .and_then(|leaf| leaf.strip_prefix('v'))
        .unwrap_or_else(|| panic!("snapshot `{}` is not <spec>/v<version>", snapshot))
        .to_string();

    let snap_dir = repo.join("spec-data").join(&snapshot);
    let manifest = snap_dir.join("MANIFEST.md");
    if !manifest.is_file() {
        panic!(
            "REFUSING TO BUILD: the requirements declare snapshot `{}` but {} does not exist. \
             The suite would otherwise claim a snapshot it never read.",
            snapshot,
            manifest.display()
        );
    }
    println!("cargo:rerun-if-changed={}", manifest.display());

    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("snapshot.rs");
    std::fs::write(
        &out,
        format!(
            "// GENERATED by build.rs — derived from the requirement files' own `snapshot` field.\n\
             pub const SNAPSHOT: &str = {snapshot:?};\n\
             pub const SPEC_VERSION: &str = {version:?};\n\
             pub const SNAPSHOT_MANIFEST: &[u8] = include_bytes!({manifest:?});\n",
            snapshot = snapshot,
            version = version,
            manifest = path_str(&manifest),
        ),
    )
    .expect("write snapshot.rs");
}

fn path_str(p: &Path) -> String {
    p.to_str().expect("non-utf8 path").to_string()
}

/// Pull `"snapshot": "<value>"` out of a `.diag` file without a JSON parser — the value is a
/// plain string and a dependency here would be a dependency in the suite's build.
fn extract_snapshot(body: &str) -> Option<String> {
    for line in body.lines() {
        let t = line.trim();
        let Some(rest) = t.strip_prefix("\"snapshot\"") else { continue };
        let Some(rest) = rest.trim_start().strip_prefix(':') else { continue };
        let Some(rest) = rest.trim_start().strip_prefix('"') else { continue };
        let Some(end) = rest.find('"') else { continue };
        return Some(rest[..end].to_string());
    }
    None
}
